apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

android {
    namespace "asia.chumbaka.kayam.launcher"
    compileSdkVersion 30
    buildToolsVersion '30.0.3'
    
    defaultConfig {
        multiDexEnabled true
        minSdkVersion 30
        targetSdkVersion 30
        applicationId "asia.chumbaka.kayam.launcher"
        versionCode 1
        versionName "1.0.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        debug {
            storeFile file('../debug.keystore')
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
        release {
            if (project.hasProperty("RELEASE_STORE_FILE")) {
                storeFile file(RELEASE_STORE_FILE)
                storePassword RELEASE_STORE_PASSWORD
                keyAlias RELEASE_KEY_ALIAS
                keyPassword RELEASE_KEY_PASSWORD
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            if (project.hasProperty("RELEASE_STORE_FILE")) {
                signingConfig signingConfigs.release
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    dexOptions {
        javaMaxHeapSize "4g"
        preDexLibraries = false
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    
    // AndroidX dependencies
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'androidx.multidex:multidex:2.0.1'
    
    // Testing
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    
    // Local libs
    implementation files('libs/commons-net-3.6.jar')
    implementation files('libs/commons-io-2.5.jar')
    implementation files('libs/zxing.jar')
    
    // Other dependencies
    implementation 'org.apmem.tools:layouts:1.10@aar'
    implementation project(':kitkitlogger')
    
    implementation('com.github.bumptech.glide:glide:4.12.0') {
        exclude group: 'com.android.support'
    }

    implementation 'com.google.firebase:firebase-auth:20.0.4'
    implementation 'com.google.firebase:firebase-storage:19.2.2'
}
